#include "shaderlib/cshader.h"
class lux_post_alphablend_ps30_Static_Index
{
public:
	lux_post_alphablend_ps30_Static_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_lux_post_alphablend_ps30 1


class lux_post_alphablend_ps30_Dynamic_Index
{
public:
	lux_post_alphablend_ps30_Dynamic_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_lux_post_alphablend_ps30 1

