//====== Copyright © 1996-2006, Valve Corporation, All rights reserved. =======
//
// Purpose: 
//
//=============================================================================

#include "tf_gamerules.h"

#ifndef ACHIEVEMENTS_TF_H
#define ACHIEVEMENTS_TF_H

#ifdef _WIN32
#pragma once
#endif

// Putting these here makes it easier to find and configure.
#define ACHIEVEMENT_TF2C_TRANQ_TORTURE_DURATION_REQUIREMENT					10.0f
#define ACHIEVEMENT_TF2C_CALCULATED_ROCKET_DISTANCE_REQUIREMENT				1200.0f
#define ACHIEVEMENT_TF2C_NEST_DESTROYER_DESTRUCTION_REQUIREMENT				5
#define ACHIEVEMENT_TF2C_LOYAL_SERVANT_HEALING_REQUIREMENT					5000
//#define ACHIEVEMENT_TF2C_INFLICT_TRANQUILIZATION_REQUIREMENT				10
#define ACHIEVEMENT_TF2C_TRANQ_MELEE_KILL_REQUIREMENT						10
#define ACHIEVEMENT_TF2C_EXTINGUISH_BOMBLETS_REQUIREMENT					20

// 2.1.0 Pack
#define ACHIEVEMENT_TF2C_AA_VS_AIRBORNE_REQUIREMENT							9
#define ACHIEVEMENT_TF2C_TRANQ_COUNTER_KILL_REQUIREMENT						5
#define ACHIEVEMENT_TF2C_TRANQ_KILL_DISTANCE								350
#define ACHIEVEMENT_TF2C_TRANQ_SUPPORT_PROGRESSION_REQUIREMENT				2000
#define ACHIEVEMENT_TF2C_TRANQ_HIT_BLASTJUMP_HEIGHT							100
#define ACHIEVEMENT_TF2C_MINES_UNSEEN_DAMAGE_REQUIREMENT					5000
#define ACHIEVEMENT_TF2C_MINES_STREAK_SINGLE_LIFE_REQUIREMENT				16
#define ACHIEVEMENT_TF2C_MINES_TRIGGER_WITHOUT_HURT_REQUIREMENT				8
#define ACHIEVEMENT_TF2C_STICKY_PRIMED_KILLS_REQUIREMENT					30
#define ACHIEVEMENT_TF2C_SURF_ENEMY_MINE_DISTANCE							750

#define ACHIEVEMENT_TF2C_REVOLVER_KILLS_SINGLE_LIFE_REQUIREMENT				3

#define ACHIEVEMENT_TF2C_HARVESTER_DECAP_SINGLE_LIFE_REQUIREMENT			3
#define ACHIEVEMENT_TF2C_HARVESTER_COUNTER_LOW_HEALTH_REQUIREMENT			5
#define ACHIEVEMENT_TF2C_HARVESTER_COUNTER_LOW_HEALTH_THRESHOLD				30

#define ACHIEVEMENT_TF2C_FIRE_AXE_DEATH_AFTERBURN_REQUIREMENT				1000

#define ACHIEVEMENT_TF2C_HEAVY_SHOTGUN_CRITS_REQUIREMENT					20

#define ACHIEVEMENT_TF2C_TELEPORTER_PROGRESSION_REQUIREMENT					10000
#define ACHIEVEMENT_TF2C_JUMPPAD_PROGRESSION_REQUIREMENT					1000
#define ACHIEVEMENT_TF2C_JUMPPAD_PROGRESSION_ASSIST_REQUIREMENT				20
#define ACHIEVEMENT_TF2C_JUMPPAD_PROGRESSION_DESTROYED_REQUIREMENT			40
#define ACHIEVEMENT_TF2C_AIR_COMBAT_HEIGHT									100
#define ACHIEVEMENT_TF2C_HEADSHOT_KILL_MIDFLIGHT_HEIGHT						100


#define ACHIEVEMENT_TF2C_VIP_PROTECT_UNSEEN_REQUIREMENT						2000
#define ACHIEVEMENT_TF2C_KILLSTREAK_WHILE_VIP_BOOSTED_REQUIREMENT			3
#define ACHIEVEMENT_TF2C_VIP_TEAMMATE_KILLSTREAK_DAMAGE_BOOST_REQUIREMENT	3
#define ACHIEVEMENT_TF2C_VIP_TEAMMATE_PROGRESSION_HASTE_REQUIREMENT			10
#define ACHIEVEMENT_TF2C_VIP_KILL_CRIT_KILLSTREAK_REQUIREMENT				2
#define ACHIEVEMENT_TF2C_KILL_VIP_DAMAGERS_REQUIREMENT						20
#define ACHIEVEMENT_TF2C_KILL_VIP_DAMAGERS_LAST_DAMAGE_TIME					5.0f // seconds
#define ACHIEVEMENT_TF2C_PROTECT_VIP_AS_MEDIC_DISTANCE_SQ					512.0f
#define ACHIEVEMENT_TF2C_PROTECT_VIP_AS_MEDIC_LAST_DAMAGE_TIME				5.0f // seconds

#define ACHIEVEMENT_TF2C_MINIGUN_DAMAGE_STREAK_AMOUNT						1000
#define ACHIEVEMENT_TF2C_MINIGUN_DAMAGE_STREAK_TIMER						10.0f
#define ACHIEVEMENT_TF2C_MINIGUN_DUEL_REQUIREMENT							10

#define ACHIEVEMENT_TF2C_SPEEDWATCH_SPEED_KILL_TIMER						15.0f
//#define ACHIEVEMENT_TF2C_INVIS_RECHARGE_CLOAKED_START_AT					0.7f							
#define ACHIEVEMENT_TF2C_AA_GUN_SPLASH_REQUIREMENT							2000
#define ACHIEVEMENT_TF2C_AA_GUN_CHALLENGE_COUNTER							2000
#define ACHIEVEMENT_TF2C_SSG_SCOUT_HIT_PELLETS_MULTI_COUNT					20
#define ACHIEVEMENT_TF2C_SSG_MEATSHOTS_REQUIREMENT							10
#define ACHIEVEMENT_TF2C_SSG_MEATSHOTS_MIN_MULTI_COUNT						16								
#define ACHIEVEMENT_TF2C_SSG_POUNCE_REQUIREMENT								5						
#define ACHIEVEMENT_TF2C_SSG_POUNCE_TIMER									4.0f
#define ACHIEVEMENT_TF2C_PYRO_SHOTGUN_CORESHOT_STREAK_SHOTS					3
#define ACHIEVEMENT_TF2C_PYRO_SHOTGUN_CORESHOT_STREAK_MIN_MULTICOUNT		7
#define ACHIEVEMENT_TF2C_PYRO_SHOTGUN_CORESHOT_STREAK_TIMER					5.0f	
#define ACHIEVEMENT_TF2C_PYRO_SHOTGUN_CORESHOT_REQUIREMENT					6



// retired stuff below	
#define ACHIEVEMENT_TF2C_TEAMMATE_KILLSTREAK_HASTE_BOOST_REQUIREMENT		3
#define ACHIEVEMENT_TF2C_SOVIET_UNION_ASSIST_REQUIREMENT					5
//#define ACHIEVEMENT_TF2C_EXTREME_SHOCK_THERAPY_TARGET_HEALTH				30
#define ACHIEVEMENT_TF2C_BODYSHOT_MEDIC_REQUIREMENT							3
#define ACHIEVEMENT_TF2C_TRANQ_MELEE_KILL_TEAMMATE_ASSIST_REQUIREMENT		4
#define ACHIEVEMENT_TF2C_TRANQ_TEAMMATE_ASSIST_REQUIREMENT					20
#define ACHIEVEMENT_TF2C_STICKY_MINES_REMOVAL_REQUIREMENT					40
#define ACHIEVEMENT_TF2C_POP_THE_MEDIC_REQUIREMENT							3
#define ACHIEVEMENT_TF2C_MINES_LONG_RANGE_DISTANCE							1000
#define ACHIEVEMENT_TF2C_MINES_LONG_RANGE_REQUIREMENT						2000
#define ACHIEVEMENT_TF2C_REVOLVER_BUILDING_SABOTAGE_REQUIREMENT				6
#define ACHIEVEMENT_TF2C_HARVESTER_HEAL_PROGRESSION_REQUIREMENT				2000
#define ACHIEVEMENT_TF2C_CHEKHOV_CLOSE_MELEE_KILLS_REQUIREMENT				9
#define ACHIEVEMENT_TF2C_CHEKHOV_CLOSE_MELEE_KILLS_DISTANCE					200
#define ACHIEVEMENT_TF2C_SCOUT_BATTING_HEAVY_REQUIREMENT					5
#define ACHIEVEMENT_TF2C_JUMPPAD_KILL_ON_USE_REQUIREMENT					10
#define ACHIEVEMENT_TF2C_JUMPPAD_JUMP_AND_SAP_REQUIREMENT					3
#define ACHIEVEMENT_TF2C_VIP_HEAL_OTHERS_REQUIREMENT						5000
#define ACHIEVEMENT_TF2C_HEALED_BY_VIP_REQUIREMENT							1000	
#define ACHIEVEMENT_TF2C_HEAL_MILESTONE_REQUIREMENT							1000000
#define ACHIEVEMENT_TF2C_SPEEDWATCH_CLOAK_CHALLENGE_COUNTER					3
#define ACHIEVEMENT_TF2C_AA_GUN_DEFENCE_COUNTER								3
#define ACHIEVEMENT_TF2C_AA_GUN_DEFENCE_RANGE								512.0f	
#define ACHIEVEMENT_TF2C_MINIGUN_VS_HEAVY_REQUIREMENT						5
#define ACHIEVEMENT_TF2C_MINIGUN_KILLSTREAK_COUNTER							3
#define ACHIEVEMENT_TF2C_MINIGUN_KILLSTREAK_TIMER							5.0f	
#define ACHIEVEMENT_TF2C_PYRO_RAW_REQUIREMENT								10
#define ACHIEVEMENT_TF2C_WIZARD_REQUIREMENT									1337
#define ACHIEVEMENT_TF2C_POP_INVULN_HEALTH									50
#define ACHIEVEMENT_TF2C_MULTIPLE_UBERS_PER_LIFE_REQUIREMENT				3
#define ACHIEVEMENT_TF2C_BOTTLE_MASTERY_REQUIREMENT							5
#define ACHIEVEMENT_TF2C_QWTF_DM_REQUIREMENT								3
#define ACHIEVEMENT_TF2C_HEAL_PROGRESSION_REQUIREMENT						100000
#define ACHIEVEMENT_TF2C_FIRE_PROGRESSION_REQUIREMENT						55555



enum
{
	TF2C_ACHIEVEMENT_START								= 0,
	BLANKED_TF2C_ACHIEVEMENT_BETA_PARTICIPANT_BLANKED,																			// The first, now unobtainable, achievement.
	TF2C_ACHIEVEMENT_PACK_TEAMFORTRESS2CLASSIC_BEGIN,
	TF2C_ACHIEVEMENT_KILL_WITH_DISTANTRPG				= TF2C_ACHIEVEMENT_PACK_TEAMFORTRESS2CLASSIC_BEGIN,		// The beginning of the "Team Fortress 2 Classic" achievement pack.
	TF2C_ACHIEVEMENT_KILL_BUILDINGS_WITH_MIRV,
	BLANKED_TF2C_ACHIEVEMENT_INFLICT_TRANQUILIZATION_BLANKED,	// Blanked due to new remake ach
	TF2C_ACHIEVEMENT_DEFUSE_MIRV,
	TF2C_ACHIEVEMENT_PLAY_GAME_CLASSICMAPS_1,
	TF2C_ACHIEVEMENT_DOMINATE_DEVELOPER,	// This achievement now applies to anyone with a medal
	BLANKED_TF2C_ACHIEVEMENT_KILL_DEMO_WITH_OWNMIRV_BLANKED,	// Blanked due to new remake ach
	TF2C_ACHIEVEMENT_KILL_WITH_BLINDCOILRICOCHET,
	TF2C_ACHIEVEMENT_TRANQ_MELEE_KILL,	// Used to be TF2C_ACHIEVEMENT_INFLICT_TRANQUILIZATION
	TF2C_ACHIEVEMENT_EXTINGUISH_BOMBLETS,	// Used to be TF2C_ACHIEVEMENT_KILL_DEMO_WITH_OWNMIRV
	TF2C_ACHIEVEMENT_PACK_TEAMFORTRESS2CLASSIC_END		= TF2C_ACHIEVEMENT_EXTINGUISH_BOMBLETS,					// The end of the "Team Fortress 2 Classic" achievement pack.

	TF2C_ACHIEVEMENT_PACK_GAMEMODES_AND_MAPS_BEGIN		= TF2C_ACHIEVEMENT_PACK_TEAMFORTRESS2CLASSIC_END + 1,
	TF2C_ACHIEVEMENT_WIN_CIVILIAN_NODEATHS				= TF2C_ACHIEVEMENT_PACK_GAMEMODES_AND_MAPS_BEGIN,
	TF2C_ACHIEVEMENT_HEAL_CIVILIAN,
	TF2C_ACHIEVEMENT_DOMINATE_CIVILIAN,
	TF2C_ACHIEVEMENT_PLAY_GAME_VIPMAPS_1,
	TF2C_ACHIEVEMENT_KILL_CIVILIAN_DISGUISEBOOST,
	TF2C_ACHIEVEMENT_PACK_VIP_EXTRA_6,
	TF2C_ACHIEVEMENT_PACK_VIP_EXTRA_7,
	TF2C_ACHIEVEMENT_PACK_VIP_EXTRA_8,
	TF2C_ACHIEVEMENT_PACK_VIP_EXTRA_9,
	TF2C_ACHIEVEMENT_PACK_VIP_EXTRA_10,
	TF2C_ACHIEVEMENT_HOLD_ALLPOINTS_DOMINATION,
	TF2C_ACHIEVEMENT_PLAY_GAME_DOMMAPS_1,
	TF2C_ACHIEVEMENT_VIP_PROTECT_UNSEEN,
	TF2C_ACHIEVEMENT_KILLSTREAK_WHILE_VIP_BOOSTED,
	TF2C_ACHIEVEMENT_VIP_TEAMMATE_KILLSTREAK_DAMAGE_BOOST,
	BLANKED_TF2C_ACHIEVEMENT_VIP_TEAMMATE_PROGRESSION_HASTE_BLANKED,
	TF2C_ACHIEVEMENT_VIP_KILL_CRIT_KILLSTREAK,
	TF2C_ACHIEVEMENT_KILL_VIP_DAMAGERS,
	TF2C_ACHIEVEMENT_PROTECT_VIP_AS_MEDIC,
	TF2C_ACHIEVEMENT_4TEAM_BACKSTAB,
	TF2C_ACHIEVEMENT_ARCHAEOLOGY,
	TF2C_ACHIEVEMENT_PACK_GAMEMODES_AND_MAPS_END		= TF2C_ACHIEVEMENT_ARCHAEOLOGY,

	TF2C_ACHIEVEMENT_PACK_STOCK_BEGIN					= TF2C_ACHIEVEMENT_PACK_GAMEMODES_AND_MAPS_BEGIN + 150,
	TF2C_ACHIEVEMENT_TELEPORTER_PROGRESSION = TF2C_ACHIEVEMENT_PACK_STOCK_BEGIN,
	TF2C_ACHIEVEMENT_TELEPORTER_ENEMY_SPY_KILL,
	TF2C_ACHIEVEMENT_INVIS_RECHARGE_CLOAKED,
	TF2C_ACHIEVEMENT_REVOLVER_KILLS_SINGLE_LIFE,
	TF2C_ACHIEVEMENT_STICKY_PRIMED_KILLS,
	TF2C_ACHIEVEMENT_PYRO_SHOTGUN_CORESHOT_STREAK,
	TF2C_ACHIEVEMENT_FIRE_AXE_DEATH_AFTERBURN,
	TF2C_ACHIEVEMENT_FLARE_CRIT_TEAMWORK,
	TF2C_ACHIEVEMENT_MINIGUN_DUEL,
	TF2C_ACHIEVEMENT_FISTS_MELEE_DUEL,
	TF2C_ACHIEVEMENT_PACK_STOCK_END = TF2C_ACHIEVEMENT_FISTS_MELEE_DUEL,

	TF2C_ACHIEVEMENT_PACK_DEATH_AND_TAXES_BEGIN = TF2C_ACHIEVEMENT_PACK_STOCK_BEGIN + 100,
	TF2C_ACHIEVEMENT_TRANQ_KILL = TF2C_ACHIEVEMENT_PACK_DEATH_AND_TAXES_BEGIN,
	TF2C_ACHIEVEMENT_TRANQ_MELEE_KILL_AS_TEAMMATE,
	TF2C_ACHIEVEMENT_TRANQ_SUPPORT_PROGRESSION,
	TF2C_ACHIEVEMENT_TRANQ_HIT_BLASTJUMP,
	TF2C_ACHIEVEMENT_TRANQ_COUNTER_KILL,
	TF2C_ACHIEVEMENT_MINES_UNSEEN_DAMAGE,
	TF2C_ACHIEVEMENT_MINES_STREAK_SINGLE_LIFE,
	TF2C_ACHIEVEMENT_MINES_TRIGGER_WITHOUT_HURT,
	TF2C_ACHIEVEMENT_SANDVICH_MINES,
	TF2C_ACHIEVEMENT_SURF_ENEMY_MINE,
	TF2C_ACHIEVEMENT_TAUNT_KILL_MIRV,
	TF2C_ACHIEVEMENT_PACK_DEATH_AND_TAXES_END = TF2C_ACHIEVEMENT_TAUNT_KILL_MIRV,

	TF2C_ACHIEVEMENT_PACK_FIGHT_AND_FLIGHT_BEGIN = TF2C_ACHIEVEMENT_PACK_DEATH_AND_TAXES_BEGIN + 100,
	TF2C_ACHIEVEMENT_AIR_COMBAT = TF2C_ACHIEVEMENT_PACK_FIGHT_AND_FLIGHT_BEGIN,
	TF2C_ACHIEVEMENT_HEADSHOT_KILL_MIDFLIGHT,
	TF2C_ACHIEVEMENT_HARVESTER_COLLECT_DECAP,
	TF2C_ACHIEVEMENT_HARVESTER_DECAP_SINGLE_LIFE,
	TF2C_ACHIEVEMENT_HARVESTER_COUNTER_LOW_HEALTH,
	TF2C_ACHIEVEMENT_HARVESTER_COUNTER_SPY,
	TF2C_ACHIEVEMENT_JUMPPAD_STOMP,
	TF2C_ACHIEVEMENT_JUMPPAD_EXTINGUISH,
	TF2C_ACHIEVEMENT_JUMPPAD_PROGRESSION,
	TF2C_ACHIEVEMENT_JUMPPAD_PROGRESSION_ASSIST,
	TF2C_ACHIEVEMENT_JUMPPAD_PROGRESSION_DESTROYED,
	TF2C_ACHIEVEMENT_JUMPPAD_ENEMY_SPY_BACKSTAB,
	TF2C_ACHIEVEMENT_AA_VS_AIRBORNE,
	TF2C_ACHIEVEMENT_AA_GUN_SPLASH,
	TF2C_ACHIEVEMENT_AA_GUN_CHALLENGE,
	TF2C_ACHIEVEMENT_AA_GUN_BLAST_SUICIDE,
	TF2C_ACHIEVEMENT_CHEKHOV_CRIT_KILL,
	TF2C_ACHIEVEMENT_HEAVY_SHOTGUN_CRITS,
	TF2C_ACHIEVEMENT_CHEKHOV_SHOCK,
	TF2C_ACHIEVEMENT_SSG_SCOUT_HIT_PELLETS,
	TF2C_ACHIEVEMENT_SSG_MEATSHOTS,
	TF2C_ACHIEVEMENT_SSG_POUNCE,
	TF2C_ACHIEVEMENT_SPEEDWATCH_RECOVERY,
	TF2C_ACHIEVEMENT_SPEEDWATCH_SPEED_KILL,
	TF2C_ACHIEVEMENT_SPEEDWATCH_COUNTER,
	TF2C_ACHIEVEMENT_PACK_FIGHT_AND_FLIGHT_END = TF2C_ACHIEVEMENT_SPEEDWATCH_COUNTER,

	TF2C_ACHIEVEMENT_COUNT,

	/*
	* 
	// Retired section!
	// Set these again in "IsClass" functions if you use them
	// Code itself should be merely commented out in cpp file
	// Likely not have a correct xbox score and jingle set
	BLANKED_TF2C_ACHIEVEMENT_EXTREME_SHOCK_THERAPY_BLANKED,
	BLANKED_TF2C_ACHIEVEMENT_WELCOME_TO_TF2C_BLANKED,
	BLANKED_TF2C_ACHIEVEMENT_BODYSHOT_MEDIC_BLANKED,
	BLANKED_TF2C_ACHIEVEMENT_CRIT_KILL_MAP_HARVESTER_BLANKED,
	BLANKED_TF2C_ACHIEVEMENT_MINES_PREVENT_SELF_DETONATION_BLANKED,
	TF2C_ACHIEVEMENT_HEAL_MILESTONE,
	TF2C_ACHIEVEMENT_POP_THE_MEDIC,
	TF2C_ACHIEVEMENT_DISGUISE_MASTERY,
	TF2C_ACHIEVEMENT_REVOLVER_BUILDING_SABOTAGE,
	TF2C_ACHIEVEMENT_STICKY_MINES_REMOVAL,
	TF2C_ACHIEVEMENT_TNT_AIRBORNE_KILL,
	TF2C_ACHIEVEMENT_SOVIET_UNION,
	TF2C_ACHIEVEMENT_SCOUT_BATTING_HEAVY,
	TF2C_ACHIEVEMENT_PYRO_RAW,
	TF2C_ACHIEVEMENT_VIP_HEAL_OTHERS,
	TF2C_ACHIEVEMENT_HEALED_BY_VIP,
	TF2C_ACHIEVEMENT_MAP_FLOODGATE,
	TF2C_ACHIEVEMENT_MINIGUN_VS_HEAVY,
	TF2C_ACHIEVEMENT_MINIGUN_KILLSTREAK,
	TF2C_ACHIEVEMENT_DRUNKEN_MASTER,
	TF2C_ACHIEVEMENT_TRANQ_MELEE_KILL_TEAMMATE_ASSIST,
	TF2C_ACHIEVEMENT_TRANQ_TEAMMATE_ASSIST,
	TF2C_ACHIEVEMENT_MINES_JUMP_AND_DESTROY,
	TF2C_ACHIEVEMENT_MINES_LONG_RANGE,
	TF2C_ACHIEVEMENT_JUMPPAD_KILL_ON_USE,
	TF2C_ACHIEVEMENT_JUMPPAD_JUMP_AND_SAP,
	TF2C_ACHIEVEMENT_AA_GUN_DEFENCE,
	TF2C_ACHIEVEMENT_CHEKHOV_CLOSE_MELEE_KILLS,
	TF2C_ACHIEVEMENT_HARVESTER_HEAL_PROGRESSION,
	TF2C_ACHIEVEMENT_SPEEDWATCH_CLOAK_CHALLENGE,
	TF2C_ACHIEVEMENT_TEAMMATE_KILLSTREAK_HASTE_BOOST,
	TF2C_ACHIEVEMENT_MINIGUN_DAMAGE_STREAK,
	TF2C_ACHIEVEMENT_VIP_TEAMMATE_PROGRESSION_HASTE,

	//not used yet, most are dumb so wait for Foxysen
	TF2C_ACHIEVEMENT_WIZARD,
	TF2C_ACHIEVEMENT_POP_INVULN,
	TF2C_ACHIEVEMENT_DISPENSER_REQUEST,
	TF2C_ACHIEVEMENT_MULTIPLE_UBERS_PER_LIFE,
	TF2C_ACHIEVEMENT_PILLSTREAK_REACH_MAX,
	TF2C_ACHIEVEMENT_TAUNT_KILL_HADOUKEN,
	TF2C_ACHIEVEMENT_TAUNT_KILL_SHOWDOWN,
	TF2C_ACHIEVEMENT_TAUNT_KILL_SPINAL_TAP,
	TF2C_ACHIEVEMENT_TAUNT_KILL_SKEWER,
	TF2C_ACHIEVEMENT_TAUNT_KILL_FENCING,
	TF2C_ACHIEVEMENT_SKEWER_STUN_INVULN,
	TF2C_ACHIEVEMENT_BOTTLE_MASTERY,
	TF2C_ACHIEVEMENT_NAILGUN_DESTROY_SENTRY,
	TF2C_ACHIEVEMENT_MEDIC_TOP_MVP,
	TF2C_ACHIEVEMENT_KILL_PILLSTREAK_MAX_USER,
	TF2C_ACHIEVEMENT_QWTF_DM,
	TF2C_ACHIEVEMENT_FIREAXE_ON_SNIPER,
	TF2C_ACHIEVEMENT_FIRE_PROGRESSION,																				// The last achievement.

	*/
};

#endif // ACHIEVEMENTS_TF_H