#ifndef ACHIEVEMENTS_220_TF_H
#define ACHIEVEMENTS_220_TF_H

#include "achievements_tf.h"

#define ACHIEVEMENT_TF2C_HEAL_MILESTONE_REQUIREMENT_NADER							500000

enum
{
	// 2.2!!!!!!!!!!!
	TF2C_ACHIEVEMENT_PACK_2POINT2_BEGIN = TF2C_ACHIEVEMENT_PACK_FIGHT_AND_FLIGHT_BEGIN + 100,
	TF2C_ACHIEVEMENT_ANCHOR_EARTHQUAKE,
	TF2C_ACHIEVEMENT_ANCHOR_AIRSHOTCRIT,
	TF2C_ACHIEVEMENT_ANCHOR_NO_ROCKET,
	TF2C_ACHIEVEMENT_BATTLE_MEDIC,
	TF2C_ACHIEVEMENT_CANE_COLLECT_BOOST,
	TF2C_ACHIEVEMENT_HEAL_MILESTONE_NADER,
	TF2C_ACHIEVEMENT_EXTEND_UBER,
	TF2C_ACHIEVEMENT_UBER_MANY,
	TF2C_ACHIEVEMENT_KILL_SENTRY_WITH_NAILGUN,
	TF2C_ACHIEVEMENT_DESTROY_PROJ_CYCLOPS,
	TF2C_ACHIEVEMENT_CYCLOPS_AIRBORNE,
	TF2C_ACHIEVEMENT_CYCLOPS_BLIND,
	TF2C_ACHIEVEMENT_CYCLOPS_HUGECOMBO,
	TF2C_ACHIEVEMENT_PACK_2POINT2_END = TF2C_ACHIEVEMENT_CYCLOPS_HUGECOMBO,
};

#endif // ACHIEVEMENTS_220_TF_H